name: Merge Workflow

on:
  push:
    branches:
      - master

jobs:
  Build_Publish_Azure_DevOps_CLI_Extension:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install setuptools
      run: pip install setuptools
    - uses: ./.github/actions/setup-ci-machine/action.yml
    - uses: ./.github/actions/build-publish-azure-devops-cli-extension/action.yml

  Build_Publish_Azure_CLI_Test_SDK:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install setuptools
      run: pip install setuptools
    - uses: ./.github/actions/setup-ci-machine/action.yml
    - uses: ./.github/actions/build-publish-azure-cli-test-sdk/action.yml

  Run_Test_Windows:
    needs: [Build_Publish_Azure_CLI_Test_SDK, Build_Publish_Azure_DevOps_CLI_Extension]
    runs-on: windows-latest
    steps:
    - run: ren "C:\Program Files\Common Files\AzureCliExtensionDirectory" "C:\Program Files\Common Files\AzureCliExtensionDirectory1"
      shell: powershell
    - uses: ./.github/actions/run-tests/action.yml
      with:
        pythonVersion: '3.8'
    - name: Build wheel for Azure DevOps CLI extension
      run: python setup.py sdist bdist_wheel
      working-directory: azure-devops/

  Run_Test_Ubuntu:
    needs: [Build_Publish_Azure_CLI_Test_SDK, Build_Publish_Azure_DevOps_CLI_Extension]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.10]
    steps:
    - run: sudo rm -R -f /usr/local/lib/azureExtensionDir
    - uses: ./.github/actions/run-tests/action.yml
      with:
        pythonVersion: ${{ matrix.python-version }}

  Run_Test_Mac:
    needs: [Build_Publish_Azure_CLI_Test_SDK, Build_Publish_Azure_DevOps_CLI_Extension]
    runs-on: macos-latest
    steps:
    - uses: ./.github/actions/run-tests/action.yml
      with:
        pythonVersion: '3.10'

  Run_Test_Mac_Azure_CLI_Released_Version:
    needs: Build_Publish_Azure_CLI_Test_SDK
    runs-on: macos-latest
    steps:
    - uses: ./.github/actions/run-tests/action.yml
      with:
        pythonVersion: '3.10'
        runWithAzureCliReleased: 'true'

  Code_Coverage:
    needs: Build_Publish_Azure_CLI_Test_SDK
    runs-on: macos-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - uses: ./.github/actions/install-azure-cli-edge/action.yml
    - uses: ./.github/actions/download-install-local-azure-test-sdk/action.yml
    - uses: ./.github/actions/setup-ci-machine/action.yml
    - uses: ./.github/actions/download-install-local-azure-devops-cli-extension/action.yml
    - name: Run unit tests for code coverage
      run: pytest --junitxml "TEST-UT-results.xml" --cov=azext_devops/dev --cov-report=xml --cov-report=html
      working-directory: azure-devops
    - name: Install beautifulsoup4
      run: pip install beautifulsoup4
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Fix Code Coverage Style
      run: python scripts/fixCodeCoverageStyle.py
    - uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: |
          $(System.DefaultWorkingDirectory)/azure-devops/coverage.xml
          $(System.DefaultWorkingDirectory)/azure-devops/htmlcov/**/*.*

  Run_Style_Check:
    runs-on: macos-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - uses: ./.github/actions/install-azure-cli-edge/action.yml
    - uses: ./.github/actions/download-install-local-azure-test-sdk/action.yml
    - uses: ./.github/actions/setup-ci-machine/action.yml
    - uses: ./.github/actions/download-install-local-azure-devops-cli-extension-with-pip/action.yml
    - name: Run Style Check
      run: powershell scripts/runStyleCheck.ps1

  Run_HelpText_Check:
    needs: Build_Publish_Azure_CLI_Test_SDK
    runs-on: macos-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - uses: ./.github/actions/install-azure-cli-edge/action.yml
    - uses: ./.github/actions/download-install-local-azure-test-sdk/action.yml
    - uses: ./.github/actions/setup-ci-machine/action.yml
    - name: Install Azure DevOps CLI extension
      run: pip install --upgrade .
      working-directory: azure-devops/
    - name: Run HelpText Check
      run: python scripts/findEmptyHelpTexts.py

  Run_Test_From_Old_Release:
    needs: Build_Publish_Azure_CLI_Test_SDK
    runs-on: macos-latest
    steps:
    - run: git checkout release-1.0.1
    - uses: ./.github/actions/run-tests/action.yml
      with:
        pythonVersion: '3.10'
        runOnlyRecordedTests: 'true'

  Check_Back_Compat_Arguments:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - uses: ./.github/actions/setup-ci-machine/action.yml
    - uses: ./.github/actions/install-azure-cli-edge/action.yml
    - name: Build wheel for Azure DevOps CLI extension
      run: python setup.py sdist bdist_wheel
      working-directory: azure-devops/
    - name: Run Back Compat Argument Check
      run: python scripts/backCompatChecker.py

  Run_Markdown_Lint_Check:
    runs-on: windows-latest
    steps:
    - name: Install chef utils
      run: gem install chef-utils -v 16.6.14
    - name: Install markdown lint
      run: gem install mdl
    - name: Run markdown lint
      run: mdl . -c .mdlrc
