name: Released Version Workflow

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Run_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Set up virtual environment
        continue-on-error: true
        run: |
          python -m venv env
          source env/bin/activate
          pip install wheel==0.30.0 setuptools==70.0.0
          pip install azdev
          azdev --version
          azdev setup -r ./ -e azure-devops
          azdev extension repo add .
          azdev extension add azure-devops
          azdev test azure-devops --live --no-exitfirst --series
        env:
          AZURE_DEVOPS_EXT_TEST_ORG: ${{ secrets.AZURE_DEVOPS_EXT_TEST_ORG }}
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_EXT_PAT }}

      - name: Publish Recordings
        uses: actions/upload-artifact@v4
        with:
          name: recordings
          path: ${{ github.workspace }}/azure-devops/azext_devops/tests/latest/integrationtests/recordings