name: Released Version Workflow

on:
  schedule:
    workflow_dispatch: - cron: "0 0 * * *"

jobs:
  Build_Publish_Azure_CLI_Test_SDK:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          architecture: x64
      - name: Install setuptools
        run: pip install setuptools==70.0.0
      - uses: ./.github/actions/setup-ci-machine
      - uses: ./.github/actions/build-publish-azure-cli-test-sdk

  Run_Test:
    needs: Build_Publish_Azure_CLI_Test_SDK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          architecture: x64
      - uses: ./.github/actions/install-azure-cli-edge
      - uses: ./.github/actions/download-install-local-azure-test-sdk
      - uses: ./.github/actions/setup-ci-machine    
      - name: Install azure devops extension from azure cli index
        run: az extension add -n azure-devops --debug
      - name: Run Tests
        run: pytest --junitxml "TEST-results.xml"        
      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: '**TEST-*.xml'
